# Generated by Django 2.0.7 on 2018-07-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_order',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
